DROP TABLE IF EXISTS epbs_registry;

CREATE TABLE epbs_registry (
    "rowId" BIGSERIAL PRIMARY KEY,

    "lastUpdateFrom" TIMESTAMP NOT NULL,
    "lastUpdateTo" TIMESTAMP NOT NULL,

    -- RubpEntry
    "id" VARCHAR,

    -- RubpEntryInfo
    "regNum" VARCHAR,
    "code" VARCHAR,
    "divisionParentName" VARCHAR,
    "divisionParentCode" VARCHAR,
    "ogrn" VARCHAR,
    "fullName" VARCHAR,
    "shortName" VARCHAR,
    "inn" VARCHAR,
    "kpp" VARCHAR,
    "regDate" TIMESTAMP,
    "okopfName" VARCHAR,
    "okopfCode" VARCHAR,
    "okfsName" VARCHAR,
    "okfsCode" VARCHAR,
    "postIndex" VARCHAR,
    "cityType" VARCHAR,
    "cityName" VARCHAR,
    "streetType" VARCHAR,
    "streetName" VARCHAR,
    "house" VARCHAR,
    "oktmoName" VARCHAR,
    "oktmoCode" VARCHAR,
    "orfkName" VARCHAR,
    "orfkCode" VARCHAR,
    "oksmName" VARCHAR,
    "oksmCode" VARCHAR,
    "location" VARCHAR,
    "kbkName" VARCHAR,
    "kbkCode" VARCHAR,
    "okoguName" VARCHAR,
    "okoguCode" VARCHAR,
    "okpoCode" VARCHAR,
    "orgTypeName" VARCHAR,
    "orgTypeCode" VARCHAR,
    "establishmentKindName" VARCHAR,
    "establishmentKindCode" VARCHAR,
    "legalPersonKindName" VARCHAR,
    "legalPersonKindCode" VARCHAR,
    "ougvName" VARCHAR,
    "ougvCode" VARCHAR,
    "uoName" VARCHAR,
    "uoCode" VARCHAR,
    "creatorKindName" VARCHAR,
    "creatorKindCode" VARCHAR,
    "creatorPlaceName" VARCHAR,
    "creatorPlaceCode" VARCHAR,
    "founderKindName" VARCHAR,
    "founderKindCode" VARCHAR,
    "founderPlaceName" VARCHAR,
    "founderPlaceCode" VARCHAR,
    "budgetLvlName" VARCHAR,
    "budgetLvlCode" VARCHAR,
    "budgetName" VARCHAR,
    "budgetCode" VARCHAR,
    "statusCode" VARCHAR,
    "statusName" VARCHAR,
    "regionType" VARCHAR,
    "regionName" VARCHAR,
    "isOGV" VARCHAR,
    "isObosob" VARCHAR,
    "orgStatus" VARCHAR,
    "recordNum" VARCHAR,
    "parentCode" VARCHAR,
    "parentName" VARCHAR,
    "okatoCode" VARCHAR,
    "okatoName" VARCHAR,
    "guid" VARCHAR,
    "status" VARCHAR,
    "controlNum" VARCHAR,
    "bidNum" VARCHAR,
    "firstRegDate" TIMESTAMP,
    "firstRegGuid" VARCHAR,
    "lastRegGuid" VARCHAR,
    "lastRegDate" TIMESTAMP,
    "lastRegNum" VARCHAR,
    "updateReason" VARCHAR,
    "updateNum" VARCHAR,
    "inclusionDate" TIMESTAMP,
    "exclusionDate" TIMESTAMP,
    "pubpCode" VARCHAR,
    "rubpCode" VARCHAR,
    "nubpCode" VARCHAR,
    "cpzCode" VARCHAR,
    "pgmyCode" VARCHAR,
    "firmName" VARCHAR,
    "kofkCode" VARCHAR,
    "nameDocs" VARCHAR,
    "accMgmt" VARCHAR,
    "naibznachuch" VARCHAR,
    "regionCode" VARCHAR,
    "areaCode" VARCHAR,
    "areaType" VARCHAR,
    "areaName" VARCHAR,
    "cityCode" VARCHAR,
    "localCode" VARCHAR,
    "localName" VARCHAR,
    "localType" VARCHAR,
    "streetCode" VARCHAR,
    "building" VARCHAR,
    "apartment" VARCHAR,
    "reformationDocument" VARCHAR,
    "reformationDocumentNum" VARCHAR,
    "reformationDocumentDate" TIMESTAMP,
    "reformationName" VARCHAR,
    "reformationCode" VARCHAR,
    "reformationStartDate" TIMESTAMP,
    "reformationEndDate" TIMESTAMP,
    "dateUpdate" TIMESTAMP,
    "isExcluded" VARCHAR,
    "isReorg" VARCHAR,
    "startDate" TIMESTAMP,
    "endDate" TIMESTAMP,
    "loadDate" TIMESTAMP,
    "regionKladrCode" VARCHAR,
    "egrulnotincluded" VARCHAR,
    "parentrecordnum" VARCHAR,
    "planningstructuretype" VARCHAR,
    "planningstructurename" VARCHAR,
    "contourTypeCode" VARCHAR,
    "specEventCode" VARCHAR,
    "speceventcodedop1" VARCHAR,
    "speceventcodedop2" VARCHAR,
    "speceventcodedop3" VARCHAR,
    "dsp" TEXT,
    "isUch" VARCHAR,
    "reforfkCode" VARCHAR,

    -- authorities (RubpEntryAuthority)
    "auth_authorityCode" VARCHAR,
    "auth_authorityName" VARCHAR,
    -- вложенный массив внутри authorities -> permissions (RubpEntryAuthorityPermissions)
    "auth_perm_permissionCode" VARCHAR,
    "auth_perm_permissionName" VARCHAR,

    -- activities (RubpEntryActivity)
    "act_activityCode" VARCHAR,
    "act_activityName" VARCHAR,
    "act_activityKind" VARCHAR,

    -- heads (RubpEntryHead)
    "head_fio" VARCHAR,
    "head_post" VARCHAR,
    "head_docName" VARCHAR,
    "head_docNum" VARCHAR,
    "head_docDate" TIMESTAMP,
    "head_headMain" VARCHAR,

    -- successions (RubpEntrySuccession)
    "succ_parentName" VARCHAR,
    "succ_parentCode" VARCHAR,
    "succ_ogrn" VARCHAR,
    "succ_docname" VARCHAR,
    "succ_numberdoc" VARCHAR,
    "succ_documentdate" TIMESTAMP,
    "succ_datasource" VARCHAR,

    -- facialAccounts (RubpEntryAccountFK)
    "fa_kindName" VARCHAR,
    "fa_kindCode" VARCHAR,
    "fa_num" VARCHAR,
    "fa_createDate" TIMESTAMP,
    "fa_closeDate" TIMESTAMP,
    "fa_status" VARCHAR,
    "fa_openUfkCode" VARCHAR,
    "fa_openUfkName" VARCHAR,
    "fa_openTofkName" VARCHAR,
    "fa_srvUfkCode" VARCHAR,
    "fa_srvUfkName" VARCHAR,
    "fa_accountorgcode" VARCHAR,
    "fa_accountorgfullname" VARCHAR,
    "fa_ppocode" VARCHAR,
    "fa_pponame" VARCHAR,
    "fa_refsrvUfkCode" VARCHAR,
    "fa_refopenUfkCode" VARCHAR,

    -- foAccounts (RubpEntryAccountFO)
    "fo_foName" VARCHAR,
    "fo_foCode" VARCHAR,
    "fo_accountTypeName" VARCHAR,
    "fo_num" VARCHAR,

    -- participantPermissions (RubpEntryParticipantPermission)
    "part_perm_name" VARCHAR,
    "part_perm_code" VARCHAR,
    "part_perm_startDate" TIMESTAMP,
    "part_perm_endDate" TIMESTAMP,

    -- nonParticipantPermissions (RubpEntryNonParticipantPermission)
    "npart_perm_name" VARCHAR,
    "npart_perm_registryNum" VARCHAR,
    "npart_perm_code" VARCHAR,
    "npart_perm_startDate" TIMESTAMP,
    "npart_perm_endDate" TIMESTAMP,
    "npart_perm_authBudgName" VARCHAR,
    "npart_perm_authBudgCode" VARCHAR,
    "npart_perm_authPPOName" VARCHAR,
    "npart_perm_authPPOCode" VARCHAR,
    "npart_perm_authKBKGlavaName" VARCHAR,
    "npart_perm_authKBKGlavaCode" VARCHAR,

    -- procurementPermissions (RubpEntryProcurementPermission)
    "proc_perm_name" VARCHAR,
    "proc_perm_code" VARCHAR,
    "proc_perm_startDate" TIMESTAMP,
    "proc_perm_endDate" TIMESTAMP,

    -- contacts (RubpEntryContact)
    "cont_phone" VARCHAR,
    "cont_site" VARCHAR,
    "cont_mail" VARCHAR,

    -- acceptAuths (RubpEntryAcceptAuth)
    "ac_auth_name" VARCHAR,
    "ac_auth_code" VARCHAR,
    "ac_auth_startDate" TIMESTAMP,
    "ac_auth_endDate" TIMESTAMP,
    "ac_auth_authBudgName" VARCHAR,
    "ac_auth_authBudgCode" VARCHAR,
    "ac_auth_authPPOName" VARCHAR,
    "ac_auth_authPPOCode" VARCHAR,
    "ac_auth_authKBKGlavaName" VARCHAR,
    "ac_auth_authKBKGlavaCode" VARCHAR,
    "ac_auth_authGiverCode" VARCHAR,
    "ac_auth_authGiverName" VARCHAR,
    "ac_auth_userArea" VARCHAR,
    "ac_auth_authRegNum" VARCHAR,

    -- transfauth (RubpEntryTransfAuth)
    "tr_auth_authfovillagescode" VARCHAR,
    "tr_auth_authfovillagesname" VARCHAR,
    "tr_auth_authfomunicipalcode" VARCHAR,
    "tr_auth_authfomunicipalname" VARCHAR,
    "tr_auth_authstartdate" TIMESTAMP,
    "tr_auth_authenddate" TIMESTAMP,
    "tr_auth_kbkglavacode" VARCHAR,
    "tr_auth_budgetcode" VARCHAR,
    "tr_auth_authregnum" VARCHAR,
    "tr_auth_authfovillagesppocode" VARCHAR,
    "tr_auth_authfovillagespponame" VARCHAR,

    -- attachment (RubpEntryAttachment)
    "attach_id" VARCHAR,
    "attach_name" VARCHAR,
    "attach_mime" VARCHAR,

    -- contracts (RubpEntryContract)
    "contr_contractnumber" VARCHAR,
    "contr_signdate" TIMESTAMP,
    "contr_orgcodecontract" VARCHAR,
    "contr_orgnamecontract" VARCHAR,

    -- ubptransfauthbp (RubpEntryUbpTransfAuthbp)
    "ubp_bp_ppocode" VARCHAR,
    "ubp_bp_pponame" VARCHAR,
    "ubp_bp_budlevelnsiname" VARCHAR,
    "ubp_bp_budlevelnsicode" VARCHAR,
    "ubp_bp_budgetnsiname" VARCHAR,
    "ubp_bp_budgetnsicode" VARCHAR,
    "ubp_bp_codebk" VARCHAR,
    "ubp_bp_headname" VARCHAR,

    -- ubptransfauthbu (RubpEntryUbpTransfAuthbu)
    "ubp_bu_authbuauthorgcode" VARCHAR,
    "ubp_bu_authbuauthname" VARCHAR,
    "ubp_bu_authbustartdate" TIMESTAMP,
    "ubp_bu_authbuenddate" TIMESTAMP,

    -- ubpfin (RubpEntryUbpfin)
    "fin_findocname" VARCHAR,
    "fin_findocnum" VARCHAR,
    "fin_findocdate" TIMESTAMP,

    -- ksaccounts (RubpEntryKsAccount)
    "ks_num" VARCHAR,
    "ks_opendate" TIMESTAMP,
    "ks_closedate" TIMESTAMP,
    "ks_opentofkcode" VARCHAR,
    "ks_opentofkname" VARCHAR,
    "ks_refsrvufkcode" VARCHAR,
    "ks_accountvidname" VARCHAR,
    "ks_ppocode" VARCHAR
    )