services:
  postgres-db:
    image: postgres:latest
    container_name: scraper_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: etl
      POSTGRES_PASSWORD: etl
      POSTGRES_DB: scraper_database
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: